const mongoose = require('mongoose')
const oempSchema = new mongoose.Schema(

    {
        cod: Number,
        geo: String,
        sigla_mun: String,
        nome_mun: String,
        uf: String,
        cn: Number,
        gram: String,
        gra: String,
        pp: String,
        protocolo: Number,
        osCrm: String,
        numeroba: Number,
        localidade: String,
        circuito: String,
        num_circuito: String,
        produto: String,
        velocidade_de: String,
        vel_de: String,
        velocidade: String,
        vel: String,
        servico: String,
        pove: String,
        tipoOS: String,
        tipoR1: String,
        posto: String,
        pend: String,
        descricao: String,
        diretoria: String,
        gerencia: String,
        area: String,
        atividade: String,
        linha: String,
        cnpj: String,
        cnpj_raiz: String,
        conglomerado: String,
        projeto: String,
        NomedoCliente: String,
        segm: String,
        ea: String,
        ger_ge: String,
        ge: String,
        data_entrada: Date,
        TempoPosto: Number,
        prazoPosto: String,
        data_abertura: Date,
        TempoVida: Number,
        prazoVida: String,
        data_agendamento: Date,
        condicao_ag: String,
        data_promessa_ori: Date,
        data_primeiro_apz: Date,
        data_ultimo_apz: Date,
        nome_solicitante: String,
        matric_tecnico_resp: String,
        obsAbertura: String,
        obsPend: String,
        itxIsento: String,
        interconexao: String,
        num_prot_anatel_cir: String,
        local_cir: String,
        meio_acesso_cir: String,
        produto_cir: String,
        servico_cir: String,
        status_cir: String,
        posto_cir: String,
        pend_cir: String,
        cliente_cir: String,
        modelo_roteador: String,
        desc_roteador: String,
        tipo_roteador: String,
        wifi: String,
        fonte: String,
        uf_a: String,
        gra_a: String,
        estacao_a: String,
        loc_end_a: String,
        codigo_logr_a: String,
        trecho_logr_a: String,
        uf_b: String,
        gra_b: String,
        estacao_b: String,
        loc_end_b: String,
        codigo_logr_b: String,
        trecho_logr_b: String,
        TecnologiaAcesso: String,
        acesso_existente: String,
        pend_ftth: String,
        oempCompany: String,
        status: String,
        obsStatus: String,
        contractDate: Date,
        oempDeadLine: Number,
        deliveryPrediction: Date,
        currentPrediction: Date,
        installationDate: Date,
        installationFee: Number,
        monthlyPayment: Number,
        contractTime: String,
        feasibilityCode: String,
        oempDesignation: String,
        accountable: String
    },
    {
        collection: 'os_abertas'
    }

)

module.exports = { Mongoose: mongoose, OempSchema: oempSchema }